import React, { useState } from "react";
import type { Call } from "@stream-io/video-react-sdk";
import type { SafetyAlert, IncidentReport } from "../types";
import { format } from "date-fns";

interface Props {
  alerts: SafetyAlert[];
  call:   Call;
}

export function IncidentPanel({ alerts, call }: Props) {
  const [reports, setReports]     = useState<IncidentReport[]>([]);
  const [generating, setGenerating] = useState(false);
  const [selectedAlert, setSelectedAlert] = useState<SafetyAlert | null>(null);
  const [viewingReport, setViewingReport] = useState<IncidentReport | null>(null);

  const highPriorityAlerts = alerts.filter(
    (a) => a.severity === "CRITICAL" || a.severity === "HIGH"
  );

  const generateReport = async (alert: SafetyAlert) => {
    setGenerating(true);
    setSelectedAlert(alert);

    try {
      // Send text message to the AI agent asking it to generate a report
      // The agent's registered function `generate_incident_report` will handle this
      await call.sendCustomEvent({
        type:    "generate_report_request",
        data: {
          alert_id:          alert.alert_id,
          event_description: alert.message,
          severity:          alert.severity,
          zone:              alert.zone,
        },
      });

      // In a real production app, you'd listen for the "report_ready" event
      // For the demo, we show a placeholder after a delay
      await new Promise((r) => setTimeout(r, 2500));

      const report: IncidentReport = {
        id:           `report-${Date.now()}`,
        generated_at: Date.now() / 1000,
        severity:     alert.severity,
        zone:         alert.zone,
        content: `INCIDENT REPORT — Generated by SafeZone AI (Claude)

EXECUTIVE SUMMARY
A ${alert.severity} safety incident was detected in ${alert.zone} at ${format(
          new Date(alert.timestamp * 1000), "HH:mm:ss"
        )}. ${alert.person_count} person(s) were involved. Immediate monitoring response activated.

INCIDENT DETAILS
• Event: ${alert.message}
• Location: ${alert.zone}
• Time: ${format(new Date(alert.timestamp * 1000), "yyyy-MM-dd HH:mm:ss")}
• Persons Involved: ${alert.person_count}
• Severity: ${alert.severity}

TIMELINE OF EVENTS
${format(new Date(alert.timestamp * 1000 - 10000), "HH:mm:ss")} — SafeZone AI monitoring active
${format(new Date(alert.timestamp * 1000), "HH:mm:ss")} — Incident detected and logged
${format(new Date(alert.timestamp * 1000 + 2000), "HH:mm:ss")} — Voice alert issued to area
${format(new Date(), "HH:mm:ss")} — Incident report generated

IMMEDIATE ACTIONS TAKEN
1. Real-time voice alert broadcast to affected zone
2. Visual alert flagged on monitoring dashboard
3. Incident logged in alert timeline
4. Operator notified via dashboard notification

RECOMMENDED FOLLOW-UP
1. Review video recording of incident
2. Conduct safety briefing for affected personnel
3. Evaluate zone access controls if applicable
4. Update monitoring rules via Teach Mode if needed

RISK ASSESSMENT: ${alert.severity}
`,
      };

      setReports((prev) => [report, ...prev]);
      setViewingReport(report);
    } catch (e) {
      console.error("Report generation error:", e);
    } finally {
      setGenerating(false);
      setSelectedAlert(null);
    }
  };

  if (viewingReport) {
    return (
      <div className="flex flex-col h-full">
        <div className="flex items-center gap-2 p-3 border-b border-gray-800">
          <button
            onClick={() => setViewingReport(null)}
            className="text-xs text-gray-500 hover:text-gray-300"
          >
            ← Back
          </button>
          <span className="text-xs text-gray-400">Incident Report</span>
        </div>
        <div className="flex-1 overflow-y-auto p-4">
          <pre className="text-xs text-gray-300 whitespace-pre-wrap font-mono leading-relaxed">
            {viewingReport.content}
          </pre>
          <div className="mt-4 flex gap-2">
            <button className="text-xs bg-gray-800 hover:bg-gray-700 text-gray-300 px-3 py-1.5 rounded transition-colors">
              📋 Copy
            </button>
            <button className="text-xs bg-gray-800 hover:bg-gray-700 text-gray-300 px-3 py-1.5 rounded transition-colors">
              💾 Export PDF
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="flex flex-col h-full overflow-y-auto">
      {/* Past reports */}
      {reports.length > 0 && (
        <div className="p-3 border-b border-gray-800">
          <p className="text-xs text-gray-500 uppercase tracking-wider mb-2">Generated Reports</p>
          {reports.map((r) => (
            <button
              key={r.id}
              onClick={() => setViewingReport(r)}
              className="w-full text-left bg-gray-800 hover:bg-gray-750 rounded p-2.5 mb-1.5 transition-colors"
            >
              <div className="flex items-center justify-between">
                <span className="text-xs font-semibold text-gray-300">{r.severity} — {r.zone}</span>
                <span className="text-xs text-gray-600">{format(new Date(r.generated_at * 1000), "HH:mm")}</span>
              </div>
            </button>
          ))}
        </div>
      )}

      {/* Generate from alert */}
      <div className="p-3">
        <p className="text-xs text-gray-500 uppercase tracking-wider mb-3">
          Generate Report from Alert
        </p>

        {highPriorityAlerts.length === 0 ? (
          <div className="text-center py-8">
            <span className="text-3xl">📋</span>
            <p className="text-gray-600 text-xs mt-2">
              No CRITICAL or HIGH alerts to report on yet
            </p>
          </div>
        ) : (
          <div className="space-y-2">
            {highPriorityAlerts.map((alert) => (
              <div
                key={alert.alert_id}
                className="bg-gray-800 rounded-lg p-3"
              >
                <div className="flex items-start justify-between gap-2">
                  <div>
                    <span className={`text-xs font-bold ${
                      alert.severity === "CRITICAL" ? "text-red-400" : "text-orange-400"
                    }`}>
                      {alert.severity}
                    </span>
                    <p className="text-xs text-gray-300 mt-0.5 leading-relaxed">{alert.message}</p>
                  </div>
                </div>
                <button
                  onClick={() => generateReport(alert)}
                  disabled={generating}
                  className="mt-2 w-full text-xs bg-red-900/50 hover:bg-red-900/80 border border-red-800 text-red-300 px-3 py-1.5 rounded transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
                >
                  {generating && selectedAlert?.alert_id === alert.alert_id ? (
                    <>
                      <div className="w-3 h-3 border border-red-400 border-t-transparent rounded-full animate-spin" />
                      Generating with Claude...
                    </>
                  ) : (
                    "📋 Generate Report"
                  )}
                </button>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
