# -*- coding: utf-8 -*-
"""
incident_reporter.py

Handles:
1. Claude-powered incident report generation
2. Teach Mode event handling (frontend custom events)
"""

import json
import logging
import os
from datetime import datetime
from typing import Any

import anthropic
from agents.safety_processor import SafetyProcessor

logger = logging.getLogger("safezone.reporter")


def register_incident_functions(agent: Any, processor: SafetyProcessor) -> None:
    """
    Register report generation and check available SDK event methods.
    Event subscription is handled in join_call() in main.py using agent.subscribe().
    """
    processor.generate_report = lambda desc, sev="HIGH", zone="general": \
        generate_incident_report(processor, desc, sev, zone)
    processor.add_rule = lambda rule: _add_rule(processor, rule)

    # Log available methods for debugging
    available = [m for m in dir(agent) if not m.startswith("_")]
    logger.info(f"Agent methods available: {[m for m in available if 'event' in m.lower() or 'subscribe' in m.lower() or 'on' == m]}")
    logger.info("All SafeZone functions registered")


async def generate_incident_report(
    processor: SafetyProcessor,
    event_description: str,
    severity: str = "HIGH",
    zone: str = "general",
) -> str:
    logger.info(f"Generating incident report: {event_description}")

    recent_alerts = processor.get_recent_alerts(n=15)
    stats         = processor.get_stats_snapshot()
    timestamp     = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    prompt = f"""You are a professional workplace safety officer writing an incident report.

INCIDENT DETAILS:
- Time: {timestamp}
- Severity: {severity}
- Zone: {zone}
- Description: {event_description}

RECENT ALERT HISTORY:
{json.dumps(recent_alerts, indent=2)}

MONITORING STATISTICS:
{json.dumps(stats, indent=2)}

Write a concise professional incident report with:
1. Executive Summary (2-3 sentences)
2. Incident Details (what, where, when)
3. Timeline of Events
4. Immediate Actions Taken
5. Recommended Follow-up Actions
6. Risk Assessment: {severity}

Under 400 words. Professional tone. Plain text only."""

    try:
        client   = anthropic.Anthropic(api_key=os.getenv("ANTHROPIC_API_KEY"))
        response = client.messages.create(
            model="claude-opus-4-6",
            max_tokens=1024,
            messages=[{"role": "user", "content": prompt}],
        )
        report = response.content[0].text
        logger.info("Incident report generated by Claude")
        return report
    except Exception as e:
        logger.error(f"Claude report generation failed: {e}")
        return _fallback_report(event_description, severity, zone, timestamp, recent_alerts)


def _fallback_report(desc, severity, zone, timestamp, recent):
    lines = [
        f"INCIDENT REPORT - {timestamp}",
        f"Severity: {severity} | Zone: {zone}",
        f"Description: {desc}", "",
        "RECENT ALERTS:",
    ]
    for a in recent[-5:]:
        dt = datetime.fromtimestamp(a["timestamp"]).strftime("%H:%M:%S")
        lines.append(f"  [{dt}] {a['severity']} - {a['message']}")
    return "\n".join(lines)


async def _add_rule(processor: SafetyProcessor, rule: str) -> str:
    processor.add_custom_rule(rule)
    return f"Rule added: '{rule}'"